name: GitHub Activity Box

on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches: master

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: AlphaKennyBudy/gh-box@v1.0.5
        env:
          GH_TOKEN: ${{ secrets.GH_GIST_BOX }}
          GIST_ID: 1296d82f1b44ee26e6ade56a303f0b19
          CONSIDER_PRIVATE: true
