name: COVID Box

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: puf17640/covid-box@master
        env:
          GH_PAT: ${{ secrets.GH_GIST_BOX }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COUNTRY: india
          GIST_ID: ea38144f7e9b6cd15e6cf35596901c48
