name: GitHub Activity Box

on:
  schedule:
    - cron: "* * * * *"
  push:
    branches: master

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: yohix/gh-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 1296d82f1b44ee26e6ade56a303f0b19
          CONSIDER_PRIVATE: true
