name: GitHub Activity Box

on:
  schedule:
    - cron: "* * * * *"
  push:
    branches: master

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: yohix/gh-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: c8a7a5ed99f3c6c43b86407fdc95fc44
          CONSIDER_PRIVATE: true
